### ISSUE TITLE
Unhashable type QFont for `BodeDemo.py` example

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/qwt#1]
Under python 3.4 / Qt4, I get this error.

````
  File "basedir34\build\winpython-3.4.3.amd64\python-3.4.3.amd64\lib\site-package\qwt\text_engine.py", line 70, in fontmetrics
    fm = self._fm_cache.get(font)
TypeError: unhashable type: 'QFont'
````

**Comment by PierreRaybaut** [comment]
Ok, I'm a totally noob on github so I don't know how to close this automatically but know that it's already fixed. :)

**Comment by PierreRaybaut** [comment]
Here is the associated commit: https://github.com/PierreRaybaut/qwt/commit/a77dc1bfd86f475f0c49749b3ea45e6bd4b68eb4

**Comment by PierreRaybaut** [comment]
As it was a critical bug on Python 3 / PyQt4 platforms, I've just released a new version including the bugfix: https://github.com/PierreRaybaut/qwt/releases/tag/v6.1.2alpha3

**Comment by stonebig** [comment]
thanks !
